platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WisdomHUDDemo' do
  use_frameworks!

  pod 'SnapKit'

  # Local dev pod: reads ../WisdomHUD.podspec and pulls Source/*.swift
  pod 'WisdomHUD', :path => '../'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'WisdomHUD'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
        end
      end
    end
  end
